version: '3.9'
name: tp0

services:
    rabbitmq:
      build:
        context: ./rabbitmq
        dockerfile: rabbitmq.dockerfile
      networks:
        - testing_net
      ports:
        - "5672:5672" # puerto de RabbitMQ
        - "15672:15672" # puerto del panel de control de RabbitMQ
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:15672"]
          interval: 10s
          timeout: 5s
          retries: 10

    entry_point:
      container_name: entry_point
      image: entry_point:latest
      entrypoint: python3 /main.py
      restart: on-failure
      depends_on:
        - rabbitmq
      links: 
        - rabbitmq
      environment:
        - PYTHONUNBUFFERED=1
        - LOGGING_LEVEL=DEBUG
      networks:
        - testing_net
      volumes:
        - ./entry_point/config.ini:/config.ini
        - ./protocol/protocol.ini:/protocol.ini

    fileReader:
      container_name: fileReader
      image: file_reader:latest
      entrypoint: python3 /main.py
      environment:
        - CLI_LOG_LEVEL=DEBUG
      networks:
        - testing_net
      depends_on:
        - entry_point
      volumes:
        - ./file_reader/config.ini:/config.ini
        - ./protocol/protocol.ini:/protocol.ini
        - ./.data/:/data/
 
    broker_weather1: &broker
      container_name: broker_weather1
      image: broker:latest
      entrypoint: python3 /main.py
      restart: on-failure
      depends_on:
        - rabbitmq
      links: 
        - rabbitmq
      environment:
        - BROKER_ID=1
        - BROKER_TYPE=weather
      networks:
        - testing_net
    
    broker_stations1:
      <<: *broker
      container_name: broker_stations1
      environment:
        - BROKER_ID=1
        - BROKER_TYPE=stations

    broker_trips1:
      <<: *broker
      container_name: broker_trips1
      environment:
        - BROKER_ID=1
        - BROKER_TYPE=trips

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
